name:                small-haskell
version:             0.1.0.0
github:              "Cameron27/small-haskell"
license:             MIT
author:              "Cameron Salisbury"
maintainer:          "cam2772@gmail.com"
copyright:           "2021 Cameron Salisbury"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/small-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- HUnit
- MissingH
- directory
- unordered-containers
- silently
- main-tester
- bytestring
- process
- parallel-io
- regex-tdfa
- hashable
- parseargs
- containers
- clock

library:
  source-dirs:
  - src

executables:
  small-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - small-haskell

tests:
  small-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - small-haskell
